####  **Задание на повторение материала**
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [1]:
import numpy as np

In [2]:
a = np.arange(0, 12)
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.


In [3]:
a1 = a.reshape(2, 6)
a2 = a.reshape(3, 4)
a3 = a.reshape(4, 3)
a4 = a.reshape(6, 2)
a5 = a.reshape(1, 12)
a1, a2, a3, a4, a5

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]]),
 array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]))

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1
(в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
b1 = a.reshape(2, -1)
b2 = a.reshape(3, -1)
b3 = a.reshape(4, -1)
b4 = a.reshape(-1, 2)
b5 = a.reshape(-1, 12)
b1, b2, b3, b4, b5


(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]]),
 array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]))

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


In [5]:
b5.shape

(1, 12)

Ответ нет, это двумерный массив

6. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [6]:
b = np.random.randn(3, 4)
b

array([[-0.47332897,  0.07273801, -1.11215768,  0.51123735],
       [-0.6051009 ,  1.56920469,  0.65783135, -1.39895891],
       [-1.20853482,  0.80223765, -0.62787234, -0.34047091]])

In [7]:
b.size


12

In [8]:
b1 = b.flatten()
b1, b1.size

(array([-0.47332897,  0.07273801, -1.11215768,  0.51123735, -0.6051009 ,
         1.56920469,  0.65783135, -1.39895891, -1.20853482,  0.80223765,
        -0.62787234, -0.34047091]),
 12)

7. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.


In [14]:
a = np.arange(20, 0, -2)
a, a.shape

(array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2]), (10,))

8. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [15]:
b = (np.arange(20, 1, -2)).reshape(-1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [13]:
b.shape

(1, 10)

Ответ: Оба массива имеют по 10 элементов, однако массив а является одномерным, а массив b - двумерный

9. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [20]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [21]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
v.size

10

10. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [24]:
a = np.arange(0, 12, 1)
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [25]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [27]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

Размер матрицы B: при умножений матриц размером (4х3) и (3х4) получатеся матрица (4х4):

In [28]:
B.shape

(4, 4)

Квадратная матрица обратима тогда и только тогда, когда она невырождена, то есть её определитель не равен нулю. 
Посчитаем определитель матрицы:

In [30]:
np.linalg.det(B)



0.0

Определитель матрицы равен нулю, следовательно матрица В необратима.

11. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.


In [38]:
np.random.seed(seed=42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

12. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 


In [42]:
c = np.random.randint(0, 16, (1, 16))
c

array([[10, 14,  9, 15, 11, 11, 15, 14, 13, 13, 14, 13,  2, 11,  6,  3]])

In [43]:
c.shape

(1, 16)

13. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [45]:
C = c.reshape(4, 4)
C

array([[10, 14,  9, 15],
       [11, 11, 15, 14],
       [13, 13, 14, 13],
       [ 2, 11,  6,  3]])

In [47]:
D = C * 10 + B
D

array([[1005, 1414,  923, 1532],
       [1114, 1150, 1586, 1522],
       [1323, 1386, 1549, 1512],
       [ 232, 1222,  812,  602]])

Определитель матрицы не равен нулю:

In [48]:
np.linalg.det(D)

-247167520000.00073

Ранг матрицы: 

In [49]:
np.linalg.matrix_rank(D)

4

Обратная матрица:

In [77]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.00040254, -0.00266191,  0.00347278, -0.000968  ],
       [ 0.00021186, -0.00156643,  0.00099739,  0.00091606],
       [-0.00133475,  0.00135799, -0.00022003,  0.00051605],
       [ 0.00152542,  0.00237384, -0.00306617, -0.0005214 ]])

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [78]:
D_inv = np.array([[1 if x>0 else 0 for x in i] for i in D_inv])
D_inv

array([[0, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1],
       [1, 1, 0, 0]])

In [79]:
np.where(D_inv == 1, B, C)

array([[100, 140,  23, 150],
       [ 14, 110,  86, 122],
       [130,  86, 140, 212],
       [ 32, 122,  60,  30]])